import { createSlice } from "@reduxjs/toolkit";

export const taskSlice = createSlice({
    name: "tasks",
    initialState: {
        allTasks: [],
        taskToEdit: {},
        showTaskForm: false,
    },
    reducers: {
        addTask: (state, action) => {
            state.allTasks.push(action.payload);
        },
        updateTask: (state, action) => {
            const index = state.allTasks.findIndex(
                (task) => task.id === action.payload.id
            );
            state.allTasks[index] = action.payload;
        },
        deleteTask: (state, action) => {
            const newAllTasks = state.allTasks.filter(
                (task) => task.id !== action.payload.id
            );
            state.allTasks = newAllTasks;
        },
        addTaskToEdit: (state, action) => {
            state.taskToEdit = action.payload;
        },
        emptyTaskToEdit: (state, action) => {
            state.taskToEdit = {};
        },
        toggleForm: (state, action) => {
            state.showTaskForm = !state.showTaskForm;
        },
    },
});

// addTask action automatically generated by createSlice
// produces actions with the same name as our reducer
export const {
    addTask,
    updateTask,
    deleteTask,
    addTaskToEdit,
    emptyTaskToEdit,
    toggleForm,
} = taskSlice.actions;
// reducer automatically generated by createSlice
// contains all our reducers
export default taskSlice.reducer;
